### ISSUE TITLE
Route handler bug

### ISSUE THREAD

**Issue by neo773** [kartikk221/hyper-express#106]
Hi,

The route handler has a bug where it is executed twice when the request body has JSON and the route has a middleware

I have also attached a reproducible demo

With body
```
curl -X POST localhost:4000/api/profile -d '{ "test": "test" }'
```
Output: 
```
1659969926326
1659969926326
```

Without body

```
curl -X POST localhost:4000/api/profile
```
Output: 
```
1659969971285
```

Reproducible Demo

````
const HyperExpress = require('hyper-express')

const router = new HyperExpress.Router()
const webserver = new HyperExpress.Server()

const useAuthentication = async (request, response, next) => {
    return next()
}

const updateprofile = async (request, response) => {
    console.log(Date.now())
    response.send('ok')
}

router.post('/profile', {
    middlewares: [useAuthentication]
}, updateprofile)

webserver.use('/api/', router)

webserver.listen(4000)
````

**Comment by kartikk221** [comment]
Hi @neo773 This is not a bug in HyperExpress but rather that your middleware `useAuthentication` is incorrect. Your middleware is `async` but you also call `next()` inside of it which leads to a double iteration. If you try setting an error handler using `Server.set_error_handler` you will see the error being logged to console and that your requests are receiving a 500 HTTP response due to a server error. You may only call `next()` inside of a synchronous middleware while `async` middlewares are simply awaited internally thus not requiring you to iterate forward with the next callback.
