### ISSUE TITLE
Hot reloading / deployment

### ISSUE THREAD

**Issue by mindplay-dk** [kartikk221/hyper-express#119]
Is hot reloading supported? (I see no mention in the docs.)

I realize I could make the app restart with e.g. `nodemon`, but I'm wondering if we can do better?

If I understand correctly, you have the actual workers running out of the main thread, and communicating with them via WebSockets? If so, I'm wondering, could we achieve "zero downtime" during deployments, as well as "instant" reloading during development, by holding incoming requests while restarting the workers?

(and yeah, I also realize I could achieve that by proxying the server with NGINX or Caddy, but that seems almost like a shame - with hyper-express being so insanely fast, a proxy server is likely going to be slower than hyper-express itself. I think I'd prefer to harden the app server with production-ready middleware, achieving really simple startup and deployment...)

**Comment by kartikk221** [comment]
HyperExpress is meant to be a simple / un-opinionated web-server  similar to Express.js. For that reason, only the fundamental components are supported. Hot reloading would be a featured built on top of middlewares/route logic hence developers can roll their own or use an existing middleware based solution to achieve this functionality with HyperExpress as you would with any similar webserver.

**Comment by mindplay-dk** [comment]
Well, I didn't find an answer in the official documentation for Express.js.

Something like [express-reload](https://www.npmjs.com/package/express-reload) then?

It's two major releases behind on the `chokidar` package it depends on - it looks unmaintained.

It's all I could find though. Is this what people use?

**Comment by kartikk221** [comment]
Yeah, the thing is that Hot Reloading isn't something too common in Non-React based websites because most of the SSR will just hot reload the asset file and so when you reload the page, you will get the fresh page. For that reason, If you're unable to find a maintained package for this, you can likely roll out a version of your own that can achieve something similar. Feel free to peek at https://github.com/kartikk221/directory-sync in which I wrote two components `DirectoryMap` and `DirectoryManager` which are powered by `chokidar` and work in conjunction to allow you to watch and react/perform changes in a given directory. I would assume for hot reloading, you would inject a script in each HTML page that creates a websocket connection to the server and then simply reloads the page when the server sends an update event out.
