### ISSUE TITLE
Compatibility with express? (serving static files)

### ISSUE THREAD

**Issue by mindplay-dk** [kartikk221/hyper-express#124]
I am porting a *very* small and simple app from `express`, and I've run into many issues:

* The built-in `static` middleware isn't supported.
* You point to `live-directory` for static file serving, but this does not appear to have parity with `serve-static` (which is what `express` exposes as `static`) e.g. caching (etags) does not appear to be implemented.
* I decided to try `serve-static` instead, but the types in `@types/serve-static` don't seem to be compatible with the `use` method of `Server` in `hyper-express` - and if I bypass type-checking, it crashes with an exception.
* The `listen` method of `Server` doesn't accept the same arguments, and has a different return-type. (the `Server` API, where you immediately have access to the effective `port` number and the `close` method is definitely an improvement, but it's not compatible with Express.)

Some of these aren't big issues, and I wasn't expecting *full* compatibility with `express` by any means - but I did expect express-style middleware would at least work. Shouldn't it?

Serving static files seems like a pretty basic requirement, and the story for this seems rather incomplete right now. Practically every express app is going to need to serve some static assets. Perhaps consider adding the `static` method for better express compatibility, perhaps implemented using `live-directory`, but with the same simple API, and cache features?

The README promises "Express.js API Compatibility" - I think at least it would be reasonable to document the extent of this compatibility?

Let me know what you'd like to do, and maybe I can help.

**Comment by kartikk221** [comment]
Hi @mindplay-dk so I'll try to address aa few of the above:
- I believe almost none of the in-built middlewares of `express` are supported because they call some low level Node APIs which are not implemented with uWS.
- LiveDirectory does not support `etag` caching out of the box because it is unopinionated but such a feature can be implemented as LiveDirectory emits events for reads and updates.
- What is the exception you receive and what are the type errors you see with `serve-static`?
- The `listen` method from `express` calls then native Node `listen` method which isn't supported yet for the same reason as the first point above in that uWS is inherently different from Node.js native logic.

So the `body-parser` and `serve-static` middlewares are actually in development for `hyper-express` and will be included with the package similar to `express` once they have been finished. I just haven't had the time to work on open-source due to professional work over the past months but I do plan on getting to this sometime next month. You can track the progress of the middlewares here: https://github.com/kartikk221/hyper-express/tree/master/middlewares

I certainly see your point and will change that to "Limited Express.js API Compatibility" and potentially adding a detailed compatibility page in the future for exact information.

I do believe that 100% compatibility with Express.js is certainly possible as the Node native APIs/wrappers can be mocked on top of uWS but things do start to become complex and require a bit of planning/time at that point which is why my focus has been on developing the package for daily use and developer experience to cover the most used methods, functionalities etc.

The end goal for `hyper-express` is to have 100% API compatibility while maintaining as close to original uWS performance as possible for the best balance performance and developer experience.

I'll be closing this issue for now as this is not an immediate on-going issue that needs to be addressed for stability but feel free to follow up with further suggestions, concerns or improvements here as needed.

**Comment by mindplay-dk** [comment]
That all sounds pretty reasonable. 🙂

I'm not personally a big fan of the express low-level APIs to be honest - I personally wouldn't want the compatibility with express for anything more than access to a few common middlewares. If this can support *similar* middlewares on a simpler and cleaner foundation, I'm all for moving in a different direction.

You probably shouldn't drum up compatibility with express though, as it's not really true - it sounds like it's a long way from becoming compatible with express, and it doesn't even sound like you're certain you want to do it? Might be better to say something like "inspired by Express", as the similarities are more conceptual than actually API compatible.

Regarding your plans to implement a `serve-static` analog, do you plan on using `live-directory` for this? I would just point out one thing I noticed about that. It appears to have drastically different memory and performance characteristics from something like `serve-static` - it looks like it's keeping entire files in-memory, as well as aggressively calculating strong ETags?

That's not going to work for serving large volumes of media, e.g. audio, video, images. I believe something like `serve-static` would compute weak ETags based on file stats - it doesn't even scan directories, as far as I know, so it's designed to serve large volumes of static assets, whereas `live-directory` appears to be designed mainly as an in-memory cache for template engines?

Maybe that's not what you're planning to use at all. Do you have any code started for the `serve-static` analog? There's nothing in the repo. I've built similar things in the past, so I might be able to help.

**Comment by kartikk221** [comment]
The reality is that Express is a big part of the Node.js ecosystem and almost every developer has began or understands Express.js to a considerable extent that it is a core consideration for many when it comes to a webserver.

The express compatibility shouldn't be completely dismissed either, It isn't 100% but it isn't also something as ridiculous as 50%. For more small / medium projects that solely rely on the Express.js Request/Response methods/props, it is essentially a drag/drop type of migration but in specific cases as you encountered there is still work to be done.

LiveDirectory in its current format is a bit outdated (You can likely tell by the last activity) and in its next update, there will be more fine-tuned control over what is cached in memory vs. what is retrieved from disk along with hot reloading and passive etag generation for caching purposes. You're correct that it was originally written as an in-memory cache for template engines and limited static content such as assets.

I have not began work on `serve-static` as I was working to finish `body-parser` first, you can likely see the progress there.

I'll be sure to follow up in this repo once I begin working on `serve-static` and would appreciate any and all help!
