### ISSUE TITLE
Is there anyway this can be intergrated with react or next.js?

### ISSUE THREAD

**Issue by JackyF737** [kartikk221/hyper-express#144]
To make this even faster is there anyway for this to be integrated with react and next.js? If yes are there instructions?

**Comment by kartikk221** [comment]
Hello, so at the moment HyperExpress isn't 100% compatible with Node's native APIs and Express.js. I would assume for production ready use with React / Next.js, there would need to be 100% api compatibility first. I do plan on doing the next major increment of v7.0.0 in which I will be completely refactoring the Request/Response components along with a few others such as Server to be 100% compatible with Node.js native HTTP APIs and Express.js. This is something I plan to do likely a few months from now around Q2 of 2023.

To be clear, I haven't personally tried to utilize HyperExpress with React, but you could try and implement HyperExpress the same way you would Express into your React project in order to see If you have any success.
