### ISSUE TITLE
does this library implement the Nagle algorithm?

### ISSUE THREAD

**Issue by sebas77** [kartikk221/hyper-express#148]
Out of interest, if so can it be disabled?

**Comment by kartikk221** [comment]
All of the low-level TCP/IP communications are handled by [uWebsockets.js](https://github.com/uNetworking/uWebSockets.js) which is a Node addon for a C++ library called uWebsockets. Since `hyper-express` simply acts as a layer on top of uWebsockets.js, you would have to ask about this in the uWebsockets.js repository.
