### ISSUE TITLE
Middlewares - trailing slashes

### ISSUE THREAD

**Issue by Aderinom** [kartikk221/hyper-express#152]
Hi kartikk,

I'm currently implementing an Adapter for nestjs using hyper-express.
Currently I'm getting the swagger docs to work and now have following question/problem.

Assuming the Swagger Prefix is e.g. docs
The Swagger Doc module want's to attach following routes.
1. StaticAssets under      ` /docs/...`
2. e.g. JSON docs under  `/docs-Json`

I implemented Static Assets with a middleware like so.

```
    const [path, handler] = hyperServeStatic(dirPath, options);
    this.instance.use(path, handler);
    this.instance.get(path + '*', () => {});
```

Where the second get route just exists so requests actually get routed to the middleware.

Now I have the issue that when calling `/docs-json` the middleware under `/docs` is beeing called as well. 
This middleware is supposed to error when the file is not found (unless a certain option is set). 
(Based on I think express's serve static options, might also be nest's idk)

My thought then was that i can just scope the middleware to only `/docs/` and add a redirect from `/docs` to `/docs/` to properly route users.

However after failing to only bind the middleware to `/docs/` i scouted your code and saw following snippet.

```
  _register_middleware(pattern, middleware) {
        const record = {
            pattern: pattern.endsWith('/') ? pattern.slice(0, -1) : pattern, // Do not allow trailing slash in middlewares
            middleware,
        };
  ....
  }
```

Is there any reason trailing slashes are not allowed? 
If so. What would be the correct way to achieve /api-json not beeing influenced by the /api middleware?

**Comment by kartikk221** [comment]
The reason why middlewares aren't allowed to have trailing slashes is because middleware patterns are treated as wildcards.
For example, a middleware that has the pattern of `/api` will run on `/api/login`, `/api/register`, `/api/verify/something` etc etc.

In your case, It seems that you want to create a middleware which runs on a specific route only or at least a exactly targeted pattern. I would recommend you bind the middleware directly on the route itself If possible. You can bind middlewares specifically on a route by providing them as one of the arguments to the route creation call or by specifying the `middlewares` Array on a route.

In terms of why a `/docs` middleware is running on `/docs-Json` that seems to be a bug caused by the following line https://github.com/kartikk221/hyper-express/blob/3f1c6c9adb1fabab11ba2c3fffb26f2f2c0a6b98/src/components/router/Route.js#L73 where the request handler seems to match middlewares by starting of path instead of exact path match. 

I have gone ahead and pushed an update which fixes this bug in version `6.5.7`. Let me know If the bug still occurs or If the provided tips do not resolve your issue.
