### ISSUE TITLE
Middleware execution order

### ISSUE THREAD

**Issue by kossy360** [kartikk221/hyper-express#154]
`hyper-express`'s request handling deviates from `express` when executing middleware, making some `express` patterns impossible to replicate

```
const app = express();
const server = createServer(app);

app.use((req, res, next) => {
  console.log('global 1');
  next();
});

app.get('/test', (req, res) => {
  console.log('handler');
  res.status(200).send('All good!!');
});

app.use((req, res, next) => {
  // should not get here for "/test" requests
  console.log('global 2');
  res.status(404).send('route not found');
});

server.listen(1122);
```
A request to `/test` logs
```
global 1
handler
```
and responds with `All good!!`

with `hyper-express`
```
const server = new Server();

server. use((req, res, next) => {
  console.log('global 1');
  next();
});

server. get('/test', (req, res) => {
  console.log('handler');
  res.status(200).send('All good!!');
});

server.use((req, res, next) => {
  // should not get here for "/test" requests
  console.log('global 2');
  res.status(404).send('route not found');
});

server.listen(1122);
```
`/test` logs
```
global 1
global 2
```
and responds with `route not found`.

#### why
This pattern is typical when implementing catch-all handlers for non-existent routes and also excluding specific routes from global middleware by utilizing registration order. 

#### expectation
`hyper-express` handles the request just like `express`, global middleware should only be executed for routes registered after it.

**Comment by kartikk221** [comment]
Interesting, I wasn't aware that Express treated middlewares / route handlers based of creation order rather than path hierarchy.

Currently HyperExpress runs middlewares based on path hierarchy which yields the following order always:
1. Global
2. Path Local (Meaning bound to a specific path like '/api' -> runs on all routes '/api/*'
3. Route Local (Meaning bound to the route itself through options.middlewares or spread out as one of the handlers on a route creation call)

Since this would be a breaking change, I will add this change to the list of changes for the upcoming v7.0 rewrite which will introduce a bunch of breaking changes like above to close the compatibility gap.

**Comment by kossy360** [comment]
Thanks for the prompt response. Is there a timeline for this next major release?

Also, I'll appreciate it if I can also contribute to the effort

**Comment by kartikk221** [comment]
Hey, yeah so I'm currently busy with work but I plan on beginning the rewrite at the end of march and would likely take about 2 - 3 weeks to finish. It will be done completely in TypeScript and I'll make a separate branch for it from which contributions can be made.
