### ISSUE TITLE
Response _startAt is not being set

### ISSUE THREAD

**Issue by CodeAngel3** [kartikk221/hyper-express#157]
response `_startAt` and `_startTime` is always undefined,

it works fine on the request object.

**Comment by kartikk221** [comment]
Could you post a full code snippet showing where you set these properties and where you access these properties? Also, have you tried using `locals` property?

**Comment by CodeAngel3** [comment]
sure, here's an example.

```js
appRoutes.get('/test', async (request, response) => {

    console.log(request._startAt);
    // ^ is being set

    response.status(200).send();

    console.log(response._startAt);
    // ^ undefined

})
```

no, i have not tried using locals yet, i was hoping that this feature was already implemented

**Comment by kartikk221** [comment]
I'm confused, why would `console.log(request._startAt)` initialize it? You're simply logging a value which is undefined?

**Comment by CodeAngel3** [comment]
I assume that the value is being set somewhere in the background, `request._startAt` is being initialized while `response._startAt` is empty, this is not the case in express for example, both are initialized there.

**Comment by kartikk221** [comment]
From what you are mentioning, I would assume that `request._startAt` and `response._startAt` are both private properties used internally by Express.js, you should not be using or depending on these properties because they are not documented and thus they can break at any time between Express.js updates.

HyperExpress does not implement any form of `_startAt` property on either the request or the response for the reasons above.

I'm not sure what these values are event supposed to be but If you are aware of their behavior, then you can likely easily polyfill them in with `hyper-express` by creating a simple middleware along with the usage of the events emitted by the `Request` and `Response` objects at various points in the request lifecycle.
