### ISSUE TITLE
Share WebSockets in multithreaded applications

### ISSUE THREAD

**Issue by sn0wst0rm** [kartikk221/hyper-express#159]
Hello, I started a project based on your amazon HyperExpress server. I am at a point in which I have to manage multiple connections that will be load-balanced across multiple instances of my application, created with nodejs clusters.

Simplifying the the model, I have a client that send a "booking" request to the server (i.e. the specific cluster instance). If successful, this action has to be propagated to all the clients connected to a specific topic. In a single process application, I would simply store all the ws connections in an array and then publish a broadcast message to the ones subscribed to the topic.

In a multi process scenario, this fails since one clustered instance of the application is not aware of the connections on the others.

If Redis is unavailable for storing the sockets like in socket.io, how can I share all the ws connections across the cluster so that I can broadcast the message to all the clients?

I tried with workers but they do not fit my application scope, I would like to stay with the current configuration, using clusters.

@kartikk221 , do you have any idea on how to accomplish this task?

Thank you!

**Comment by kartikk221** [comment]
Hey, so the thing with Websockets is that a Websocket connection is a long-lived connection and as with any connection it can be owned by only a single process at any given time. For this reason, If you need to scale out websockets across mutiple processes, you have to build a sort of pub/sub and identification system.

If you only need to verticaly scale using the Node.js cluster package on a single machine with multiple processes, then you can essentialy use IPC to achieve this.

If you need to horizontally scale across multiple machines then you will have to use some sort of a central pub/sub provider and I would highly recommend Redis for this.

Below are some steps that may help you plan out system:
- You must come up with some sort of a unique identifier for each Websocket that is known by the sender machine. So for example, let's say you authenticate Websocket connections before opening them with user accounts then the user's account id would be that unique identifier.
- You can then use this unique identifier to have each process which receives a Websocket connection subscribe to Redis or listen for IPC messages from the cluster master regarding this unique identifier's communications.
- You can then also properly publish any incoming messages from the Websocket connection over Redis or through IPC to the cluster master by including the unique identifier's communications.

In essence, the unique identifier is what allows you to be able to single out the websocket connection across multiple machines and the pub/sub allows you to route communications to only those processes who want them.

Now in the scenario that the incoming websocket connections are not authenticated or associated to any given account things become a little bit more complicated but the fundamental concept remains, you have to come up with a unique identifier for each connection and in this case you would simply generate a random or some sort of a hashed identifier for the connection based on whatever information you have available about the incoming connections. You would also temporarily store this identifier in some shared database which the sender would then consume from and send out appropriate content with.

Overall, It's hard to give you an exact structure or guide on how you can build this since the exact construction of such a system is heavily dependent on your conditions and scenarios for your application but the above should give you some fundamental ideas for how you can proceed.
