### ISSUE TITLE
why removing `raw` from Request

### ISSUE THREAD

**Issue by BSN4** [kartikk221/hyper-express#171]
hi,

i'm using raw to handle files , removing it will force us to rewrite everything .. can you please bring it back?

**Comment by kartikk221** [comment]
Hi, the `Request.raw` property was removed because it was very unstable and `hyper-express` could not guarantee that the `Request.raw` would not throw a uWS forbidden access exception. However, I will add it back with more documentation and warning that this property should not be used in production and If it is, should be used through a synchronous middelware that is bounded as soon as possible to reduce the chances of a uWS forbidden access exception.

With that said, `Request.raw` has been added back in version `6.7.1` be sure to upgrade to be able to access it again.

**Comment by kartikk221** [comment]
Also, If you don't mind, could you provide your code snippet of how you are using the raw property? I just wanna make sure It isn't something hyper-express can add to prevent you from having to drop down to the raw property.

**Comment by BSN4** [comment]
here is the code being used as static file server ..

```js
import { createBrotliCompress, createGzip, createDeflate } from 'zlib';
import {HttpRequest, HttpResponse} from "uWebSockets.js";

export function sendFile(res: Response, req: Request, path: string) {
    const s = res.raw as HttpResponse
    const q = req.raw as HttpRequest
    sendFileToRes(
        s,
        {
            'if-modified-since': q.getHeader('if-modified-since'),
            range: q.getHeader('range'),
            'accept-encoding': q.getHeader('accept-encoding')
        },
        path
    );
}```

on webserver.get sync callback i just call it

**Comment by BSN4** [comment]
and thank you so much for maintaining and constantly improving this great project. Your efforts are deeply appreciated!
