### ISSUE TITLE
What am i doing wrong?

### ISSUE THREAD

**Issue by pinqtape** [kartikk221/hyper-express#175]
![image](https://github.com/kartikk221/hyper-express/assets/96379588/c053f934-3497-44ba-a694-5b625fa8411f)
![image](https://github.com/kartikk221/hyper-express/assets/96379588/d648ae03-1b47-49f3-8743-44838383943b)
I want to make a simple server to receive files from a folder, it works, but if I make a lot of requests to receive, then the server starts eating RAM in large quantities. I checked the same thing on express and there is no memory leak. please help me, I just recently started using hyper-express)

**Comment by kartikk221** [comment]
Hello, the `sendFile` method under the hood calls `Response.file()` which a method which reads the file you are sending into memory, caches it and then serves it with high performance. However, this approach will always first load the whole file into memory meaning If you have any large files or If you request a lot of different files, all of those files will be held in memory causing higher memory usage.

You have two options when it comes to this. Your approach should be to stream all files, meaning create a readable stream and then stream the file as the response. While this isn't as performant as holding the file in memory, It will ensure you do not hold a large file in memory for a long time causing high memory usage.

Once you have done the above, the next step would be to potentially optimize files that are served frequently and you are comfortable holding memory which you can then cache using something like `live-directory`

I hope the above clears things up. You have to understand serving a large amount of unique data / files is a memory intensive operation and you will high memory usage because you are having to load a high amount of bytes from disk into memory to be able to serve them in Responses.

**Comment by pinqtape** [comment]
Thank you!
