### ISSUE TITLE
Cookie is not set if response is redirected

### ISSUE THREAD

**Issue by kfrp** [kartikk221/hyper-express#181]
Hi, I am using hyper-express and the hyper-express-session libraries. It's been great! 

Now I am unable to save the session if I redirect immediately after updating the session - in my case after an oauth callback url.  I tried manually setting the cookie, that also doesn't seem to work.

My google oauth callback url is something like /auth/google/connect, and when I set the request session data (name, email) in the callback, it only persists if I also render a result from the callback url, but not if I redirect the response to another url like /dashboard. Am I doing something wrong? Let me know if you need more info.

(Meanwhile I am using the http-equiv="refresh" meta tag as a workaround.)

**Comment by kartikk221** [comment]
Hey, so the `Response.redirect` function under the hood uses the `send()` method which works writing cookies which are just headers anyways.
```js
redirect(url) {
    if (!this.completed) return this.status(302).header('location', url).send();
    return false;
}
 ```
I suspect your issue does not arise from `hyper-express` but rather some sort of cross domain security policy with cookies. There are various things you have to do when trying to set cookies across subdomains or sometimes even other domains in the form of iframes or callbacks to make sure they work.

I would recommend you utilize the Chrome Developer Tools Network Inspector to first see If your oauth callback aka. `hyper-express` is writing a `set-cookie` header on the response. Next, I would keep an eye on your console for any kind of warnings of cookies being supressed / not respected due to security policies as that is very likely the culprit.

Also, most likely you're not making this error but just in case, make sure you are calling `Response.cookie()` and setting the cookie before you do the `Response.redirect()`. Once a response has been sent, no cookies, headers, or status changes can be done.
