### ISSUE TITLE
Use HTTP url for uWebSockets.js package

### ISSUE THREAD

**Issue by ndaidong** [kartikk221/hyper-express#186]
Is it better to use HTTP url for uWebSockets.js, so it does not require git package to clone repo while installing?

Current:

```json
{
  "dependencies": {
    "uWebSockets.js": "github:uNetworking/uWebSockets.js#v20.31.0"
  }
}
```

New:

```json
{
  "dependencies": {
    "uWebSockets.js": "https://github.com/uNetworking/uWebSockets.js/archive/refs/tags/v20.31.0.tar.gz"
  }
}
```

This small change will help hyper-express work better in the containers, where git maybe not available.

**Comment by kartikk221** [comment]
Hey @ndaidong This would certainly remove the need for git package to be available while installing. However, I am not sure If the URL convention for archives on GitHub will remain consistent over the future hence If GitHub was to change the archive links then package installs may break due to requesting the direct tarball URL.

With that said, If you can provide any other information that would ensure that using the direct tarball URL is as safe and stable as using the github: convention then I would be more than glad to have this change made or merge a PR from you to do so.
