### ISSUE TITLE
adding support for bun.js

### ISSUE THREAD

**Issue by mortezaom** [kartikk221/hyper-express#187]
Hi,
I want to ask if is it possible to run the hyper-express app with bun.js, seems bunjs may make some increase in performance in most of the js projects and it may be good to have this in hyper-express if possible. or maybe any internal issue that prevents hyper-express runs with bunjs?

**Comment by kartikk221** [comment]
hyper-express is built on top of uWebsockets.js which is already much faster than Bun in benchmarks. Since hyper-express is simply a JS layer on top of uWebwockets.js, any incompatibility with Bun will be the result of something of Node.js that Bun did not implement like Streams / some native component of that sort. For that reason, there isn't a feasible way for hyper-express to add Bun support. It is either already supported or will be once Bun becomes fully compatible with Node.js / Native Addons interop which is required by uWebsockets.js
