### ISSUE TITLE
Request not found on '/' ended urls

### ISSUE THREAD

**Issue by mortezaom** [kartikk221/hyper-express#188]
Hi @kartikk221 
I was working on my API and I created a router with this structure:
![image](https://github.com/kartikk221/hyper-express/assets/32927231/f7b8776a-064a-4e2a-8f2d-9bfd2df12733)

And when I checked the Rest Client for `http://localhost:5000/api/v1` I got the response but for `http://localhost:5000/api/v1/` I got "Not Found".

is there any option in hyper-express server to fix this or not?

this is my server object:
![image](https://github.com/kartikk221/hyper-express/assets/32927231/187ee67d-f245-45fd-be49-bbc65f8ecfcd)

and these are the responses from the Rest Client:
![image](https://github.com/kartikk221/hyper-express/assets/32927231/0b275bed-85f9-451f-9a50-cd7bcebfc0de)
![image](https://github.com/kartikk221/hyper-express/assets/32927231/543f0e89-bf71-4b55-8091-632ddd8c44a8)

**Comment by kartikk221** [comment]
Hi, the reason why `http://localhost:5000/api/v1` works but `http://localhost:5000/api/v1/` does not is because they are fundamentally 2 different URLs. HyperExpress does not automatically route trail slash endings of URLs to their non trail slash routes. 

In this scenario, I would recommend adding code in your not found handler to redirect requests ending in trail slashes to their non trail slash counter parts.

Something like below would be a start:
```js
server.set_not_found_handler((request, response) => {
   // Redirect requests ending in trail slashes to non trail slash URL
   if (request.path.endsWith('/')) {
      // Remove the trailing slash from the path of the URL
      const non_trail_slash_url = request.url.replace(request.path, request.path.substring(0, request.path.length - 1));

      // Redirect the request to the non trailing slash URL
      return response.redirect(non_trail_slash_url);
   }
});
```

**Comment by ThinhVu** [comment]
@kartikk221 Does the response.redirect send 301 status to client?
If yes, then remove trail slash before route mapping is better approach.

**Comment by kartikk221** [comment]
The `Response.redirect(url`) method simply sets the HTTP status code to 302 and writes a `location` header.
https://github.com/kartikk221/hyper-express/blob/0100dd012248ebeebb9d3895642fabf7ca9fd992/src/components/http/Response.js#L698-L706

Yeah, the best approach would be to remove the trail slash before route mapping and then internally route the requests but the problem is it would be a breaking change for the current version and something that will be kept in consideration for the next major version.

**Comment by ThinhVu** [comment]
> Yeah, the best approach would be to remove the trail slash before route mapping and then internally route the requests but the problem is it would be a breaking change for the current version and something that will be kept in consideration for the next major version.

I think it's better to keep the same behavior and provide an option to let the user decide whether the trail slash would be removed or not.
