### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by pinqtape** [kartikk221/hyper-express#193]
Hi, why is there a memory leak in this code? and how to prevent it
![image](https://github.com/kartikk221/hyper-express/assets/96379588/de5a017c-18e1-403a-8be1-6463732b1746)
https://github.com/pinqtape/kartikkk

**Comment by pinqtape** [comment]
![image](https://github.com/kartikk221/hyper-express/assets/96379588/6681e197-8261-4a08-a636-2756c6ba1390)
![image](https://github.com/kartikk221/hyper-express/assets/96379588/44264185-b39c-4c85-8b32-0c09d285e48c)

**Comment by kartikk221** [comment]
You're saying that there is a memory leak in postter.js but hyper-express is not serving anything from postter.js. In fact, I am not even sure why you have hyper-express in postter.js as the job of postter.js just seems to be to send requests to hyper-express. What even is the point of creating a hyper-express server in postter.js without any routes and then listening it on port 6500?

The getter.js in which you have the hyper-express route parsing the responses as json is actually working phenomenally with very good memory usage of just ~80 MB.

The "memory leak" you are talking about in your postter.js is not a memory leak but rather your setInterval firing off a ridiculous amount of fetch requests without any throttle at all. So you aren't seeing a memory leak but a really fast memory exhaustion from all those fetch requests being made to a local server. Keep in mind, 1000 / 5 = 200 aka. your postter.js is sending out ~200 requests per second to hyper-express. This type of request ratre is nothing for hyper-express and as you can see from your getter.js, hyper-express has no trouble handling these requests. It's your postter.js which is struggling because fetch is very memory intensive, especially when you're firing off 200 requests / second.

Please review your code again carefully to notice the mistakes.

**Comment by pinqtape** [comment]
I just wanted to reproduce everything as it was in my production, you are right about hyper-express in postter, the leak is due to node-fetch, but I do not know how to solve it... thank you!
