### ISSUE TITLE
A build error appeared with version 6.14.2 with TypeScript types definition

### ISSUE THREAD

**Issue by gsfarm** [kartikk221/hyper-express#205]
`yarn build` output:

```bash
$ tsc
../node_modules/hyper-express/types/components/http/Request.d.ts:1:26 - error TS2307: Cannot find module 'qs' or its corresponding type declarations.

1 import { ParsedQs } from 'qs';
                           ~~~~

../node_modules/hyper-express/types/components/http/Request.d.ts:7:34 - error TS2307: Cannot find module 'express-serve-static-core' or its corresponding type declarations.

7 import { ParamsDictionary } from 'express-serve-static-core';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: ../node_modules/hyper-express/types/components/http/Request.d.ts:1

error Command failed with exit code 2.
```

If I've got it right, I see that `Request.d.ts` uses пакет `qs`, whereas the `querystring` package is used in the code

**Comment by kartikk221** [comment]
Hi, this issue should be fixed in the latest `v6.14.3` update. I am not sure how this went unoticed for this long since each release is ran through a Typescript check before publishing but It seems that my local machine had these libraries installed through dependencies whose behavior changed once some `@type` libraries were moved into `devDependencies`
