### ISSUE TITLE
Question:  Is there support for HTTP3 / QUIC ? 

### ISSUE THREAD

**Issue by asafcombo** [kartikk221/hyper-express#212]
In this example it seems like underlying uWebSockets has an experimental support - 

https://unetworkingab.medium.com/h3-meet-node-js-1d952e9bdd74

**Comment by kartikk221** [comment]
Hi, from what I remember, the author of uWebsockets.js had mentioned that H3 / QUIC implementation of uWebsockets.js was still in its early days and not production ready. I am not sure If things have become more mature since then but If they have, I can certainly look into implementing or merging a PR which adds H3 support.
