### ISSUE TITLE
Nest-hyper-express instance and local-pipes tests each fail one test

### ISSUE THREAD

**Issue by smolinari** [kartikk221/hyper-express#221]
Hi,

These tests fail one test. 

https://github.com/m8a-io/hyper-express-adapter/blob/90f1cd982ac2182b1abcbbff2441d7d79cfe7a2b/apps/hyper-express-test-app/tests/hello-world/e2e/hyper-express-instance.spec.ts#L45

https://github.com/m8a-io/hyper-express-adapter/blob/dev/apps/hyper-express-test-app/tests/hello-world/e2e/local-pipes.spec.ts

The application is looking for a route with the host "tenant.example.com", but simply fails with a timeout, when the host doesn't match. Should be a 404. 

![image](https://github.com/kartikk221/hyper-express/assets/3314957/fdff63e9-a49b-452a-b481-26f4a7f10c68)

Scott

**Comment by kartikk221** [comment]
Hi, have you bound a not found handler with `Server.set_not_found_handler((req, res) => {})`? Any unmatched requests will be piped to that route handler which can choose to return a 404 with any body. 

The host should not influence anything because `hyper-express` simply serves any HTTP Requests which is received on the listen port without caring about the host in any way.

See https://github.com/kartikk221/hyper-express/blob/master/docs/Server.md

**Comment by smolinari** [comment]
Hi Kartik,

Again, thanks for the reply. I'll see if I can set that handler to get the tests to pass. 

Scott

**Comment by smolinari** [comment]
Buggers.

As it seems, Nest is throwing the 500 error. The handler isn't even getting used. I have to dig deeper. 

Scott
