### ISSUE TITLE
Client certificate validation

### ISSUE THREAD

**Issue by arunnabraham** [kartikk221/hyper-express#237]
Is there any option to validate ccertificate of client requests?
like
`req.socket.getPeerCertificate()`

**Comment by kartikk221** [comment]
Hey, I don't think so. HyperExpress wraps [uWebsockets.js](https://github.com/uNetworking/uWebSockets.js). If you can find a comparable method on the `uWS.HttpResponse` instance, then you can use `Response.raw.xxx` to call that method as needed.

If you end up finding the method on `uWS.HttpRequest` then things can be a bit more complicated since uWS deallocates HttpRequest after first execution. Even in this case, what you could do is bind a global middleware as early as possible after `Server` construction and then access the `Request.raw` property inside of that middleware synchronously and cache the result on the `Request` property.
