### ISSUE TITLE
v6.15.0 introduces breaking changes with the new server.listen unix socket method

### ISSUE THREAD

**Issue by tayler-king** [kartikk221/hyper-express#242]
Prior to v6.15.0, `server.listen(port, host)` would accept a string for the port, such as `"8080"`.

With v6.15.0 it now assumes that `port` is a unix socket if it is a string. This is a breaking change and should be treated as such.

Possible hotfix if you don't want to introduce a breaking change is to check if the `host` argument has been passed, rather than checking if `port` is a string, or check if `port` is castable to a number.

**Comment by kartikk221** [comment]
This has been fixed in the recent `v6.15.1` update and casts first argument strings to the numeric port range before treating it as a unix domain socket path.

With that said, The types and documentation has always dictated the port argument should be a number and acceptance of a string was a side-effect of uWebsockets.js not enforcing its types.
