### ISSUE TITLE
Private Messaging with Websockets

### ISSUE THREAD

**Issue by kronos-999** [kartikk221/hyper-express#26]
Hi, how would one go about implementing private messaging?
In socket.io you would save and retrieve the sockets in redis and then do something like io.to(receiver_of_message).emit(....)

How would you do this here?

**Comment by kartikk221** [comment]
You cannot store the "sockets" from HyperExpress but what you can do is generate a unique identifier such as a uuid for each websocket connection and then store the websocket connection reference in a global object. Then you can simply lookup and retrieve the websocket connection from that object and send a message back to them. This implementation will only work for a single process application. If you need to perform messaging between connections over multiple processes, you would have to come up with a way to generate a unique identifier to a websocket connection that remains consistent even if the websocket connects to a different process (Think something like an IP address or a session id authenticating the websocket).

**Comment by sn0wst0rm** [comment]
Hello, I started a project based on your amazon HyperExpress server. I am at a point in which I have to manage multiple connections that will be load-balanced across multiple instances of my application, created with nodejs clusters.

Simplifying the the model, I have a client that send a "booking" request to the server (i.e. the specific cluster instance). If successful, this action has to be propagated to all the clients connected to a specific topic. In a single process application, I would simply store all the ws connections in an array and then publish a broadcast message to the ones subscribed to the topic.

In a multi process scenario, this fails since one clustered instance of the application is not aware of the connections on the others.

If Redis is unavailable for storing the sockets like in socket.io, how can I share all the ws connections across the cluster so that I can broadcast the message to all the clients?

I tried with workers but they do not fit my application scope, I would like to stay with the current configuration, using clusters.

@kartikk221 , do you have any idea on how to accomplish this task?

Thank you!
