### ISSUE TITLE
method patern isue

### ISSUE THREAD

**Issue by azkadev** [kartikk221/hyper-express#27]
I have an issue with Pat Patern

if on regular express

```app.get("/api", () => som);```

if i open the url

like ```https://url/api```
or ```https://url/api/```

it can but on hyper-express it can't

please make it similar for a pattern like express js

and for url parameters

in express like this can

```app.get("/token:id::token/:method", (req, res) => somefunc);```

please add this feature

btw sorry my english is bad

**Comment by kartikk221** [comment]
Hello, the reason why https://url/api and https://url/api/ do not work is because they are two different URLs. HyperExpress does not support automatic trailslash handling because uWebsockets.js also does not support this. You are however more than welcome to create and use your own middleware and/or router on top of HyperExpress to achieve similar functionality.

In regards to URL parameters, I'm not sure how or what the example you provided is even supposed to do. URL parameters are meant to be one parameter per path chunk. So something like:
```js
app.get('/v1/notifications/send/:topic/:priority/:ttl', (request, response) => {
    const { topic, priority, ttl } = request.path_parameters;
});
```
is how URL parameters are supposed to work with HyperExpress.
