### ISSUE TITLE
Path parameter regexp

### ISSUE THREAD

**Issue by Viper-Bit** [kartikk221/hyper-express#278]
hi @kartikk221, how about adding regexp in path (just path parameters or whole path) ?
path parameter:
```
/users/:id(\\d+)/:tab(home|photos|bio)
```

whole path example:
```
/(user|u)/:id(\\d+)
```

we can use [https://github.com/pillarjs/path-to-regexp](https://github.com/pillarjs/path-to-regexp) to convert path to regexp or checking for ( ) in `parse_path_parameters` after each recognized path parameter

**Comment by kartikk221** [comment]
- Does Express.js support a similar format?
- Is there a simpler function or methodlogy to parse and apply the regex from a path without having to depend on another library?

**Comment by Viper-Bit** [comment]
@kartikk221 

> Does Express.js support a similar format?

yes express.js exactly using path-to-regexp package
https://github.com/expressjs/express/blob/6d084715ba6ca5301e9ac1efe4309e555973b364/lib/router/layer.js#L16-L50
and also in express.js doc
https://expressjs.com/en/4x/api.html#router.METHOD

> Is there a simpler function or methodlogy to parse and apply the regex from a path without having to depend on another library?

maybe using [find-my-way](https://www.npmjs.com/package/find-my-way), fastify using find-my-way for parsing routes. based on  [router-benchmark](https://github.com/delvedor/router-benchmark) find-my-way is so much faster

**Comment by kartikk221** [comment]
I see, I will look into integrating this using native RegExp If possible for the best performance.

**Comment by MinhazurSarker** [comment]
Sounds like a bad idea

**Comment by kartikk221** [comment]
> Sounds like a bad idea

Overall, I would agree with this sentiment for the time being. I think RegExp based routes open up possibilities for unexpected behavior as the way it would work under the hood is a catch-all route which would match these requests.

Currently, the routing system for `hyper-express` is hierarchical rather than linear which is what Express.js uses and thus allowing for the request to linearly iterate through all middlewares and routes until a RegExp for a route is matched.

HyperExpress currently cannot do this effectively without sorting and enforcing an execution order for overlapping RegExp routes in some way.

Furthermore, depending on a 3rd party library like above may have negative performance implications.
