### ISSUE TITLE
Differences with nanoexpress

### ISSUE THREAD

**Issue by lughino** [kartikk221/hyper-express#3]
First of all, very good job!
I’m wondering how this project differentiates from nanoexpress?

**Comment by kartikk221** [comment]
Thanks! 
Regarding the differences between nanoexpress, I would say that since they are both based on uWebsockets.js as a base, there will only be slight differences in terms of performance. The biggest differences would be the API, maintainability and package size as nanoexpress ships with a lot of functionality that may not be desired. Since HyperExpress only implements the most important core functionalities of a webserver with the session engine being the only hard coded addition, you have a lot more flexibility. I would say both are good choices and the final decision can be made based on which functionalities are desired and which API among the two is preferred.

**Comment by lughino** [comment]
Thank you for the explanation.
Also, I noticed that the licence is different:

- hyper-express comes with MIT
- nanoexpress comes with apache2 and has a “pro” version

Considering that both relies on the same framework and the scope is
equivalent, would be nice to have a “differences” section in the readme.

**Comment by kartikk221** [comment]
Sure, I'll look into adding a differences section.
