### ISSUE TITLE
Testing on CI

### ISSUE THREAD

**Issue by benmccann** [kartikk221/hyper-express#314]
It would be helpful to maintain some confidence about changes to the codebase to have tests run against PRs. Maybe just by copying the express test suite?

**Comment by kartikk221** [comment]
> It would be helpful to maintain some confidence about changes to the codebase to have tests run against PRs. Maybe just by copying the express test suite?

So the problem is that `hyper-express` has always been slightly opinionated with an "Expres-like" API. For this reason, the project has its own tests which can be found within "tests/". For the current scope of the project, these tests serve the project well and can easily be adapted to test against PRs.

We can consider taking on the challenge of integrating the express test suite If there is a fundamental flaw in the current tests and the scope of the project expands to 100% compatibility with Express.js. Hope that clears things up. Thanks!
