### ISSUE TITLE
Add 'send' hook to Response

### ISSUE THREAD

**Issue by bompus** [kartikk221/hyper-express#4]
Currently, I see that Response has hooks for abort and complete.

I'd like to request a 'send' hook that gets fired at the top of the Response.send function, after the check to see if the response hasn't already been completed.

This would allow users to add things near the end of every request such as response time headers, set cookies for custom session handlers (similar to fastify-secure-session) , etc.

The current session logic could probably then use a global request start/response send hook, although it would take the performance hit of two hook loops.

**Comment by kartikk221** [comment]
The 'send' hook has been implemented. You can use it by upgrading to 3.2.2. I've kept the session logic in its place due to the nature of how the SessionEngine was implemented throughout the logic flow of the request handling process. The 'complete' hooks now only get fired once response has been sent without any backpressure. Regarding performance, hooks themselves will never hurt performance significantly as they are lightweight implementations, it's the operations inside the assigned hooks that can potentially hurt performance depending on usage.
