### ISSUE TITLE
How to configure express-graphql with hyper-express ?

### ISSUE THREAD

**Issue by francelwebdev** [kartikk221/hyper-express#5]
Hello, I find hyper-express really very good and I am trying to configure express-graphql with it but I cannot. Can you do an example configuration with express-graphql ? Thank you.

**Comment by kartikk221** [comment]
At the moment, HyperExpress is not 100% compatible with Express middlewares. This is because HyperExpress components have different properties/methods thus not all middlewares will work. I am currently in the process of building a middleware that can significantly increase compatibility with many existing express middlewares. Support for ExpressJS compatibility should be added over the next few updates.

**Comment by francelwebdev** [comment]
Okay. Thank you.

**Comment by kartikk221** [comment]
Update 4.0.0 was recently pushed and implemented majority of ExpressJS's Request/Response component properties/methods into HyperExpress. See if this allows express-graphql and any other express based middlewares to work with HyperExpress.
