### ISSUE TITLE
.options conflicts with .options()

### ISSUE THREAD

**Issue by flyfoxuk** [kartikk221/hyper-express#52]
I'm trying to set the preflight CORS headers prior to a POST call to the same endpoint, and having trouble establishing the `.options(path, func)` method - node complains that `webserver.options` is not a function.

It would appear the method to establish a router for the OPTIONS method conflicts with the Server/Router options object?

Other calls such as `webserver.get()`, `webserver.post()` etc all work fine, but `webserver.options()` does not work.  Docs suggest it should?

```
const webserver = new HyperExpress.Server({})

webserver.post('/hello', (request, response) => {
    return response.send('hi there')
})

webserver.options('/hello', (request, response) => {
    return response.header('Access-Control-Allow-Origin', '*').header('Access-Control-Allow-Headers', 'Content-Type, X-My-Header-Here')
})
```

**Comment by kartikk221** [comment]
I see, yeah this is a bug that is occuring because Server.options is a property which allows accessing the underlying constructor options of a Server instance but that options property overrides the Router options() method.

This has been fixed in 5.8.0 release that was just pushed out. Hope that helps!
