### ISSUE TITLE
Compatible with FeathersJS?

### ISSUE THREAD

**Issue by matiaslopezd** [kartikk221/hyper-express#61]
Hi @kartikk221! How can I make it compatible with [FeathersJS](https://github.com/feathersjs/feathers)?

**Comment by kartikk221** [comment]
HyperExpress has almost 100% compatibility with ExpressJS through implemented properties/methods on the Request/Response components. Also, HyperExpress follows the same development pattern for routers as ExpressJS. To utilize HyperExpress with FeathersJS, you would have to essentially modify the code that buils an Express instance and replace it with building a HyperExpress instance. Since FeathersJS is a framework, it will not be as simple as implementing an ExpressJS middleware which would be compatible out of the box.

I scanned the FeathersJS documentation https://docs.feathersjs.com/api/express.html#express-app and it seems that they have custom built their solution around Express itself. I would assume that you would have to fork and modify FeathersJS's specific package that exports a custom Express app to have it export a custom HyperExpress app.

**Comment by matiaslopezd** [comment]
Thank you @kartikk221!
