### ISSUE TITLE
This is more a doubt...

### ISSUE THREAD

**Issue by h2atecnologia** [kartikk221/hyper-express#63]
When hyper-express is installed, it automatically brings the uWebSockets.js package into the project.
Installing only hyper-express left the project with around 60Mb. 57Mb is just uWebSockets.js (Express 4 doesn't come close to 2Mb)
So I went to the uWebSockets.js folder and realized that binaries had been downloaded for many platforms: linux x64 / arm64, darwin x64 / arm64 and windows, for a total of 20 binaries.
If I'm running on macOS, I don't need the binaries from other platforms. I can delete these other binaries.
But... the question: for macOS Intel there are 4 files: uws_darwin_x64_83.node, uws_darwin_x64_88.node, uws_darwin_x64_93.node and uws_darwin_x64_102.node. Even if I delete some, one of them will suit me and hyper-express will still work fine.

What are these files exactly?

**Comment by kartikk221** [comment]
Hello, so uWebsockets.js is written in C++ and then compiled into a binary that is supported on each of the respective platforms most likely because I think some platforms have different low level mechanisms used in the uWebsockets.js code for execution and compatibility. Since package managers like NPM don't really have a way to filter or target packages for based on your system platform, uWebsockets.js compiles binaries for all supported platforms and simply executes the binary that is targeted for your platform during runtime. For this reason, all of the binaries are included by default in the package and hence the large size.

If your project has strict size requirements, you can manually delete the binaries that aren't targeted for your platform but uWebsockets.js does not have any proper way to do this for your system thus it includes all supported binaries.

**Comment by h2atecnologia** [comment]
Well...  if the folks from uWebSockets.js knows the reasons why each platform owns 4 files, they could put a postbuild step in the package.json and this way, remove non needed binaries.  In fact I search the knowledge about why each file to mannually remove it or... to help, create and share such postbuild.
Maybe this discussion has be in a wrong place: better in uWebSockets.js git repo. Not here. I very apreciate your attention and your quickly answers.
Thanks a lot.

**Comment by kartikk221** [comment]
Yep, this would be best suited as an issue in the uWebsockets.js repository. It just isn't something I have focused on as that is not the focus of HyperExpress. If you are able to get improvements from this issue implemented, follow up here and I'll update the uWebsockets.js version and release so you can use the lighter version of uWebsockets.js from HyperExpress.

**Comment by h2atecnologia** [comment]
Kartik,

Right after sending my previous message, I decided to go straight to the uWebSockets.js repo and "brush the bits". Right away, I opened the **build.c** file and to my surprise I came across this code snippet:

```C++
/* List of Node.js versions */
struct node_version {
    char *name;
    char *abi;
} versions[] = {
    {"v14.0.0", "83"},
    {"v15.0.0", "88"},
    {"v16.0.0", "93"},
    {"v17.0.1", "102"}
};
```

Going a little deeper: each number corresponds to a NODE_MODULE_VERSION.

See the table and the legend and the same numbers: [here]:(https://nodejs.org/en/download/releases/)

Now it seems clear to me why the 4 binaries and what they are for.

We have our answer!

**Comment by h2atecnologia** [comment]
Follows a zipped file which contains a tgz npm package which contains the same files from original uWebSockets.js npm package (57Mb). Except the original package.json file. 

It was builded through **npm pack** command in an node v14.18.1 environment (macOS High Sierra).

To see this in action, first unzip the file then type commands below:

```bash
mkdir  some_node_project
cd  $_
npm  init  -y
npm  install  folder_where_you_save_the_tgz/uws-1.0.0.tgz  -S
```

You'll must see the **postInstall.js** script in action. Go to **uws** folder in node_modules of project what you created and see what binary remained.

[uws-1.0.0.tgz.zip](https://github.com/kartikk221/hyper-express/files/8439531/uws-1.0.0.tgz.zip)
