### ISSUE TITLE
JWT Middleware Types

### ISSUE THREAD

**Issue by moiri** [kartikk221/hyper-express#74]
What is the proper way to resolve type errors when using the `jwt-express` middleware?

For now I used an unsafe cast to make it work:
```ts
import express, { MiddlewareHandler } from 'hyper-express';
import jwt from 'express-jwt';

const server = new express.Server();
server.use(jwt() as unknown as MiddlewareHandler);
```

I guess this question also holds for other third party middlewares (e.g. `bodyParser`).

**Comment by kartikk221** [comment]
Hey, would you be able to post the TypeScript errors logged when you try and use the `express-jwt` middleware? Thanks!

**Comment by moiri** [comment]
Sure, I get to following error:

```
Argument of type 'RequestHandler' is not assignable to parameter of type 'MiddlewareHandler'.
  Types of parameters 'req' and 'request' are incompatible.
    Type 'Request<DefaultRequestLocals>' is missing the following properties from type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>': accepted, host, route, signedCookies, and 48 more.
```

**Comment by kartikk221** [comment]
Hmm I see, it seems this has to do with HyperExpress not fully implementing all of the Typescript properties from ExpressJS. I would say for now, the unsafe cast you have may be the best option since you are just using the jwt middleware directly. If there was a problem with type errors when you are trying to custom logic within a middleware then It would make sense to make changes to the underlying types to reduce those errors.
