### ISSUE TITLE
Middleware for "/"

### ISSUE THREAD

**Issue by piliugin-anton** [kartikk221/hyper-express#77]
There is a bug (or feature?) when I try to add a middleware for route "/" it will be called for any route because it's matched in ...startsWith() call

**Comment by kartikk221** [comment]
Does this occur when you assign a route-specific middleware for a global route with a "/" pattern?

**Comment by piliugin-anton** [comment]
This could me my fault, after refactoring your code in my repo. But I fixed it(https://github.com/piliugin-anton/uQuik/commit/c4d96c216639d4ee70ef4dc57fe782d985acb6ae#diff-3d79637b3dbe7416b63d43a0726d25d6cb614a2481a430c6cdff90dacea52a80)

Try this code for **/test** route:
```javascript
const Server = require('./src/components/Server')

const server = new Server()

server.use((request, response, next) => {
  console.log('global middleware')
  next()
})

server.get('/', (request, response) => response.send('Hello /'))
server.use('/', (request, response, next) => {
  console.log('/ middleware')
  next()
})

server.get('/test', (request, response) => response.send('Hello /test'))
server.use('/test', (request, response, next) => {
  console.log('test middleware')
  next()
})

server
  .listen(5000, '127.0.0.1')
  .then((socket) => console.log('[server] Server started'))
  .catch((error) => console.log('[server] Failed to start a server', error))
```

**Comment by kartikk221** [comment]
I reviewed your code and received the following output when performing a request to `/` and then `/test`
![1b277d1898373bf8df02feda3211fa97](https://user-images.githubusercontent.com/55661618/173194202-4e8f0ca4-273b-411a-8fde-c0eb8b3653e9.png)

This behavior is as expected because when you specify a pattern for a middleware, that pattern is treated as a wild card. So for example, a middleware that is used on a pattern `/api` will be executed for all requests recieved over `/api/*` hence when you bind a middleware on `/`, you are effectively binding it for all requests on `/*` aka. it acts as a global middleware in its modular scope. If you can find a different behavior for this use case in Express then feel free to make a PR and I'd be glad to include it but at the moment the documented behavior of Routers/Middlewares matches the behavior you encountered.

**Comment by piliugin-anton** [comment]
Thank you for explanation. I never used express before, this is why I was confused. I thought that idea of middlewares is to be executed before controller
