### ISSUE TITLE
[Probably a bug] Streaming

### ISSUE THREAD

**Issue by piliugin-anton** [kartikk221/hyper-express#83]
I think there is a possible bug here https://github.com/kartikk221/hyper-express/blob/fb447d1eff76f018db71f71eb8e00f9143d81e6e/src/components/http/Response.js#L493 according to example from here: https://github.com/uNetworking/uWebSockets.js/blob/d52c79d5166b7579c56f419bfaf59bbd64fe1588/examples/VideoStreamer.js#L67 we should send a chunk - offset, I fixed it in my package (still not sure if it's correct): https://github.com/piliugin-anton/uQuik/commit/b9f95cf594bb39d5522f4591db12591aa7128c62
The problem appears when you have a situation when chunk is not been sent

**Comment by piliugin-anton** [comment]
I found out that offset in drain and lastOffset is the same value

**Comment by kartikk221** [comment]
Yeah, I used to actually have that sliced chunk being served for backpressuring but it's a very weird implementation and it turned out that chunk slicing was not needed because the `write()` all buffers the chunk under the hood anyways. So essentially, you should serve the next chunk after backpressure relieves rather than serve the same chunk but sliced. If you find this behavior to be incorrect, feel free to link the test code to recreate the bug in `hyper-express` and I'd be glad to push a fix.

**Comment by piliugin-anton** [comment]
The issue is stream hangs on slow internet connection when streaming a few megabytes in few files. I'm using this method `stream` to stream static files, the issue appears when I'm testing it on a production server over internet. So you may try to reproduce it by serving multiple large images over network (you may try to throttle the bandwidth in browser devtools). It may appear in future when you will be developing a middleware for static files serving

**Comment by kartikk221** [comment]
I see, I'll try to recreate this myself. If you end up writing a snippet to simulate this bug with high probability feel free to share.

**Comment by piliugin-anton** [comment]
I think i finally fixed this method issues for both: streams with size and without size

**Comment by kartikk221** [comment]
> I think i finally fixed this method issues for both: streams with size and without size

Great! Feel free to make a PR and I'd be glad to have it implemented.
