### ISSUE TITLE
[Enhancement] HyperExpress.Response should extend http.ServerResponse

### ISSUE THREAD

**Issue by UnlimitedBytes** [kartikk221/hyper-express#95]
Hello, first thanks for your awesome work,

### Describe the problem
`HyperExpress.Response` currently extends `Stream.Writable` which is fine but not express compatible.
Many famous express libraries use properties/methods of `Express.Requests`'s underlying `http.ServerResponse` and therefore don't work with a  `Stream.Writable` instance like `HyperExpress.Response`.

### Describe the proposed solution
`HyperExpress.Response` should extend the `http.ServerResponse` to make it compatible with famous express libraries that use native properties/methods of `Express.Requests`'s underlying `http.ServerResponse`. 

### Alternatives considered
Maybe provide own implementations for such famous express libraries but that could be hard/impossible to manage as there are hundreds of them..

### Importance
Would be nice to have - not insane important as it's workaround-able by hijacking the `HyperExpress.Response` to extend `http.ServerResponse`.

### Additional Information
not provided.

Best regards
UnlimitedBytes

**Comment by kartikk221** [comment]
So according to the Node.js documentation `http.ServerResponse` extends `http.OutgoingMessage` which then extends `Stream`.

After briefly looking through the docs and messing around with the constructors, It seems that the following is how you would construct an `http.ServerResponse` instance.
```js
const socket = new net.Socket(); // < This is the problem as the uWS.HttpResponse component is nowhere compatible with a net.Socket
const message = new http.IncomingMessage(socket);
const nodeResponse = new http.ServerResponse(message);
const hyperExpressResponse = new Response(nodeResponse);
```
The `net.Socket` component is fairly low level and as you can see there are about two http classes in between that are constructed and extended until you receive an `http.ServerResponse`. Even if a proper wrapper of `net.Socket` around `uWS.HttpResponse` could be written, the overhead of other constructions in between may cause degraded performance without any ability for us to optimize or modify the code of either `http.IncomingMessage` or `http.ServerResponse`.

While HyperExpress may present a very familiar API to Express, the underlying logic for processing and handling the network operations through uWS are vastly different from those of the `http` module. Since requests are essentially a flow of data coming in and going out, the decision was made to only extend `Readable` / `Writable` streams and then implement any compatibility methods that all then call the HyperExpress methods under the hood.

If you can come up with a lightweight / practical way to bridge this gap between uWS and Node HTTP further, then I would be glad to accept PRs or recommendations to do so but the above is a general breakdown of the current structure of HyperExpress.
